### ISSUE TITLE
Always uses npm to install dependencies

### ISSUE THREAD

**Issue by megadrive** [zach-hopkins/create-t3svelte-app#22]
I use `pnpm` rather than `npm`, but despite using `pnpx create-t3svelte-app`, it always uses npm to install dependencies.

I'm unsure if there's a way to detect which package manager that is being used, but either that or a new step that asks which package manager you're using when installing dependencies would be ideal.

Not super important as you can just deselect "auto install dependencies" and do it myself though.

**Comment by zach-hopkins** [comment]
Resolved with #26 - Thanks to @vishalbalaji!
