### ISSUE TITLE
Error when skipping DB setup

### ISSUE THREAD

**Issue by Lootwig** [zach-hopkins/create-t3svelte-app#3]
https://github.com/zach-hopkins/create-t3svelte-app/blob/f46cb3bbb0e3ccb7bcfebc6f7a55bbac7b6029b2/src/cli.js#L118

https://github.com/zach-hopkins/create-t3svelte-app/blob/f46cb3bbb0e3ccb7bcfebc6f7a55bbac7b6029b2/src/cli.js#L127

The second line breaks the CLI because dbAnswers is initialized as a list, not an object.

**Comment by zach-hopkins** [comment]
Thank you! Strange it's not throwing an error on my local machine from this.
